/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_CppLibraryJniTest */

#ifndef _Included_com_example_jni_CppLibraryJniTest
#define _Included_com_example_jni_CppLibraryJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_CppLibraryJniTest
 * Method:    test_add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_jni_CppLibraryJniTest_test_1add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
